version: "3"
services:
  test-mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql    
  test-postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  mysql-volume:
  postgres-volume: