spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  profiles:
    active: mysql
    include: mail

  mustache:
    servlet:
      expose-request-attributes: true
      expose-session-attributes: true
    suffix: .html

server:
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor