spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?rewriteBatchedInserts=true
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 1000
      hibernate:
        format_sql: true

logging:
  level:
    com.phcworld.web: debug
    com.phcworld.domain: debug
    org.springframework.jdbc: debug